version: '3'
services:
  php:
    image: php:8.0-apache
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html
    depends_on:
      - sqlite3
  sqlite3:
    container_name: sqlite3
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./app/src/db/phpsqlite.db:/var/www/html/src/db/phpsqlite.db
    ports:
      - '9000:9000'
    restart: unless-stopped